import { randCodeSnippet, randJSON } from '@ngneat/falso';
import type { FormatterAvailableLangConfigsType } from './types/formatters';

export function SampleCodes(lang: FormatterAvailableLangConfigsType) {
	if (lang == 'rust') {
		return `
      fn largest<'a>(str1:&'a str, str2:&'a str) -> &'a str {

if str1.len() > str2.len(){

str1
} else {
str2
}
}
fn main() {
let str1 = "Hello";let str2 = "linuxhint";
let result = largest(str1, str2);
println!("Largest: {}", result);
}`;
	}

	if (lang == 'css') {
		return `
      nav {
  ul {
    margin: 0; padding: 0; list-style: none;
  }
  li { display: inline-block; }
  a {
    display: block; padding: 6px 12px; text-decoration: none;
  }
  a {
	top: 5px;
	bottom: 15px;
}
}`;
	}

	if (lang === 'html') {
		return '<html><body><h1>Hello World!</h1></body></html>';
	}

	if (lang == 'javascript') {
		return randCodeSnippet('javascript').join('\n');
	}

	if (lang == 'typescript') {
		const codes = `LyogZXNsaW50LWRpc2FibGUgQHR5cGVzY3JpcHQtZXNsaW50L2Jhbi10cy1jb21tZW50ICovCmltcG9ydCB0eXBlIHsgT3B0aW9ucyBhcyBQcmV0dGllck9wdGlvbnMgfSBmcm9tICdwcmV0dGllcic7CmltcG9ydCB7IHJhbmRDb2RlU25pcHBldCwgcmFuZEpTT04gfSBmcm9tICdAbmduZWF0L2ZhbHNvJzsKaW1wb3J0ICogYXMgcHJldHRpZXIgZnJvbSAncHJldHRpZXIvc3RhbmRhbG9uZSc7CmltcG9ydCAqIGFzIGh0bWxQYXJzZXIgZnJvbSAncHJldHRpZXIvcGFyc2VyLWh0bWwnOwppbXBvcnQgKiBhcyBiYWJlbFBhcnNlciBmcm9tICdwcmV0dGllci9wYXJzZXItYmFiZWwnOwppbXBvcnQgKiBhcyBtYXJrZG93blBhcnNlciBmcm9tICdwcmV0dGllci9wYXJzZXItbWFya2Rvd24nOwppbXBvcnQgKiBhcyB5YW1sUGFyc2VyIGZyb20gJ3ByZXR0aWVyL3BhcnNlci15YW1sJzsKaW1wb3J0ICogYXMgdHlwZXNjcmlwdFBhcnNlciBmcm9tICdwcmV0dGllci9wYXJzZXItdHlwZXNjcmlwdCc7Ci8vIEB0cy1pZ25vcmUKaW1wb3J0ICogYXMgeG1sUGFyc2VyIGZyb20gJ0BwcmV0dGllci9wbHVnaW4teG1sJzsKLy8gQHRzLWlnbm9yZQppbXBvcnQgKiBhcyBuZ2lueFBhcnNlciBmcm9tICdwcmV0dGllci1wbHVnaW4tbmdpbngnOwppbXBvcnQgdHlwZSB7CglDb21tb25Gb3JtYXR0ZXJJbmRlbnRpb24sCglDb21tb25Gb3JtYXR0ZXJMaW5lU2VwZXJhdG9yLAoJVG9vbFNldHRpbmdzLAoJVG9vbFNldHRpbmdXaWRnZXRDb25maWdJdGVtcywKfSBmcm9tICdAZWNob28vdHlwZXMnOwppbXBvcnQgdHlwZSB7IEZvcm1hdHRlclRvb2xQcm92aWRlciB9IGZyb20gJy4uL3R5cGVzL2Zvcm1hdHRlci1wcm92aWRlcic7CmltcG9ydCB0eXBlIHsgRm9ybWF0dGVyQXZhaWxhYmxlTGFuZ0NvbmZpZ3NUeXBlIH0gZnJvbSAnLi4vdHlwZXMvZm9ybWF0dGVycyc7Cgp0eXBlIFBhcnNlcnMgPSAnanNvbicgfCAnaHRtbCcgfCAnYmFiZWwnIHwgJ21hcmtkb3duJyB8ICd5YW1sJyB8ICd0eXBlc2NyaXB0JyB8ICdzcWwnIHwgJ25naW54JzsKCmV4cG9ydCB0eXBlIFRvb2xGb3JtYXR0ZXJQcmV0dGllck9wdGlvbnNUeXBlID0gewoJaW5kZW50YXRpb24/OiBDb21tb25Gb3JtYXR0ZXJJbmRlbnRpb247CgllbmRPZkxpbmU/OiBDb21tb25Gb3JtYXR0ZXJMaW5lU2VwZXJhdG9yOwp9OwoKZXhwb3J0IGNvbnN0IFRvb2xGb3JtYXR0ZXJQcmV0dGllckRlZmF1bHRTZXR0aW5nczogVG9vbFNldHRpbmdzPFRvb2xGb3JtYXR0ZXJQcmV0dGllck9wdGlvbnNUeXBlPiA9IHsKCWluZGVudGF0aW9uOiB7CgkJYXNRdWVyeVBhcmFtczogdHJ1ZSwKCQlhc0xvY2FsU3RvcmFnZUl0ZW06IHRydWUsCgkJdmFsdWU6ICcxdCcsCgl9LAoJZW5kT2ZMaW5lOiB7CgkJYXNRdWVyeVBhcmFtczogdHJ1ZSwKCQlhc0xvY2FsU3RvcmFnZUl0ZW06IHRydWUsCgkJdmFsdWU6ICdcclxuJywKCX0sCn07CgpleHBvcnQgY2xhc3MgUHJldHRpZXJGb3JtYXR0ZXJQcm92aWRlciBpbXBsZW1lbnRzIEZvcm1hdHRlclRvb2xQcm92aWRlcjxUb29sRm9ybWF0dGVyUHJldHRpZXJPcHRpb25zVHlwZT4gewoJcGFyc2VyOiBQYXJzZXJzOwoJbGFuZzogRm9ybWF0dGVyQXZhaWxhYmxlTGFuZ0NvbmZpZ3NUeXBlOwoKCURlZmF1bHRTZXR0aW5nQ29uZmlnID0gewoJCWtleTogJ3h4eC1mb3JtYXR0ZXInLAoJCXNldHRpbmdzOiBUb29sRm9ybWF0dGVyUHJldHRpZXJEZWZhdWx0U2V0dGluZ3MsCgl9OwoKCXN0YXRpYyBXaXRoUGFyc2VyKHBhcnNlcjogUGFyc2VycywgbGFuZzogRm9ybWF0dGVyQXZhaWxhYmxlTGFuZ0NvbmZpZ3NUeXBlKSB7CgkJcmV0dXJuIG5ldyBQcmV0dGllckZvcm1hdHRlclByb3ZpZGVyKHBhcnNlciwgbGFuZyk7Cgl9CgoJU2V0dGluZ3NXaWRnZXRDb25maWcoKTogVG9vbFNldHRpbmdXaWRnZXRDb25maWdJdGVtczxUb29sRm9ybWF0dGVyUHJldHRpZXJPcHRpb25zVHlwZT4gewoJCWNvbnN0IGxhbmd1YWdlQ29uZmlnOiBUb29sU2V0dGluZ1dpZGdldENvbmZpZ0l0ZW1zPFRvb2xGb3JtYXR0ZXJQcmV0dGllck9wdGlvbnNUeXBlPiA9IFtdOwoKCQljb25zdCBzaGFyZWRDb25maWdzID0gWwoJCQl7CgkJCQlpbmRlbnRhdGlvbjogewoJCQkJCWtleTogJ2luZGVudGF0aW9uJywKCQkJCQl3aWRnZXRUeXBlOiAnY29tYm8nLAoJCQkJCWRlZmF1bHRWYWx1ZTogJzF0JywKCQkJCQlzdHlsZTogewoJCQkJCQl3aWR0aDogJzEwMHB4JywKCQkJCQl9LAoJCQkJCWNhbmRpZGF0ZXM6IFsKCQkJCQkJewoJCQkJCQkJdmFsdWU6ICcxdCcsCgkJCQkJCQlsYWJlbDogJzEgVGFiJywKCQkJCQkJfSwKCQkJCQkJewoJCQkJCQkJdmFsdWU6ICcycycsCgkJCQkJCQlsYWJlbDogJzIgU3BhY2VzJywKCQkJCQkJfSwKCQkJCQkJewoJCQkJCQkJdmFsdWU6ICc0cycsCgkJCQkJCQlsYWJlbDogJzQgU3BhY2VzJywKCQkJCQkJfSwKCQkJCQkJewoJCQkJCQkJdmFsdWU6ICdtaW5pJywKCQkJCQkJCWxhYmVsOiAnbWluaWZ5JywKCQkJCQkJfSwKCQkJCQldLAoJCQkJfSwKCQkJCWVuZE9mTGluZTogewoJCQkJCWtleTogJ2VuZE9mTGluZScsCgkJCQkJd2lkZ2V0VHlwZTogJ2NvbWJvJywKCQkJCQlkZWZhdWx0VmFsdWU6ICdccicsCgkJCQkJc3R5bGU6IHsKCQkJCQkJd2lkdGg6ICc4MHB4JywKCQkJCQl9LAoJCQkJCWNhbmRpZGF0ZXM6IFsKCQkJCQkJewoJCQkJCQkJdmFsdWU6ICdcclxuJywKCQkJCQkJCWxhYmVsOiAnQ1JMRicsCgkJCQkJCX0sCgkJCQkJCXsKCQkJCQkJCXZhbHVlOiAnXHInLAoJCQkJCQkJbGFiZWw6ICdDUicsCgkJCQkJCX0sCgkJCQkJCXsKCQkJCQkJCXZhbHVlOiAnXG4nLAoJCQkJCQkJbGFiZWw6ICdMRicsCgkJCQkJCX0sCgkJCQkJXSwKCQkJCX0sCgkJCX0sCgkJXTsKCgkJLy8gdXNlIHNoYXJlZCBjb25maWcgdG8gdXBkYXRlZCBsYW5ndWFnZSBjb25maWcgaWYgaXQgaGFzIHRoZSBzYW1lIGtleQoJCS8vIG90aGVyd2lzZSwgYWRkIGl0IHRvIHRoZSBsYW5ndWFnZSBjb25maWcKCgkJT2JqZWN0LmtleXMoc2hhcmVkQ29uZmlncykuZm9yRWFjaCgoa2V5KSA9PiB7CgkJCS8vIEB0cy1pZ25vcmUKCQkJaWYgKCFsYW5ndWFnZUNvbmZpZ1trZXldKSB7CgkJCQkvLyBAdHMtaWdub3JlCgkJCQlsYW5ndWFnZUNvbmZpZ1trZXldID0gc2hhcmVkQ29uZmlnc1trZXldOwoJCQl9CgkJfSk7CgoJCXJldHVybiBsYW5ndWFnZUNvbmZpZzsKCX0KCgljb25zdHJ1Y3RvcihwYXJzZXI6IFBhcnNlcnMsIGxhbmc6IEZvcm1hdHRlckF2YWlsYWJsZUxhbmdDb25maWdzVHlwZSkgewoJCXRoaXMucGFyc2VyID0gcGFyc2VyOwoJCXRoaXMubGFuZyA9IGxhbmc7CgoJCXRoaXMuRGVmYXVsdFNldHRpbmdDb25maWcgPSB7CgkJCWtleTogYCR7bGFuZ30tZm9ybWF0dGVyYCwKCQkJc2V0dGluZ3M6IFRvb2xGb3JtYXR0ZXJQcmV0dGllckRlZmF1bHRTZXR0aW5ncywKCQl9OwoJfQoKCUZvcm1hdCgKCQljb2RlOiBzdHJpbmcsCgkJb3B0aW9uczogewoJCQlzZXR0aW5ncz86IFRvb2xTZXR0aW5nczxUb29sRm9ybWF0dGVyUHJldHRpZXJPcHRpb25zVHlwZT47CgkJCWVycm9yQ2I/OiAoKGVycj86IEVycm9yIHwgdW5kZWZpbmVkKSA9PiB2b2lkKSB8IHVuZGVmaW5lZDsKCQl9LAoJKTogc3RyaW5nIHsKCQlsZXQgb3V0cHV0Q29kZSA9IGNvZGU7CgoJCWNvbnN0IHByZXR0aWVyT3B0aW9uczogUHJldHRpZXJPcHRpb25zID0ge307CgoJCWlmICghb3B0aW9ucy5zZXR0aW5ncykgewoJCQlvcHRpb25zLnNldHRpbmdzID0gdGhpcy5EZWZhdWx0U2V0dGluZ0NvbmZpZy5zZXR0aW5nczsKCQl9CgoJCWlmIChvcHRpb25zLnNldHRpbmdzLmluZGVudGF0aW9uKSB7CgkJCWNvbnN0IGluZGVudGF0aW9uID0gb3B0aW9ucy5zZXR0aW5ncy5pbmRlbnRhdGlvbi52YWx1ZTsKCQkJY29uc3QgZW5kT2ZMaW5lID0gb3B0aW9ucy5zZXR0aW5ncy5lbmRPZkxpbmU/LnZhbHVlOwoKCQkJc3dpdGNoIChpbmRlbnRhdGlvbikgewoJCQkJY2FzZSAnMXQnOgoJCQkJCXByZXR0aWVyT3B0aW9ucy51c2VUYWJzID0gdHJ1ZTsKCQkJCQlwcmV0dGllck9wdGlvbnMudGFiV2lkdGggPSAxOwoJCQkJCWJyZWFrOwoJCQkJY2FzZSAnMnMnOgoJCQkJCXByZXR0aWVyT3B0aW9ucy51c2VUYWJzID0gZmFsc2U7CgkJCQkJcHJldHRpZXJPcHRpb25zLnRhYldpZHRoID0gMjsKCQkJCQlicmVhazsKCQkJCWNhc2UgJzRzJzoKCQkJCQlwcmV0dGllck9wdGlvbnMudXNlVGFicyA9IGZhbHNlOwoJCQkJCXByZXR0aWVyT3B0aW9ucy50YWJXaWR0aCA9IDQ7CgkJCQkJYnJlYWs7CgkJCQljYXNlICdtaW5pJzoKCQkJCQlwcmV0dGllck9wdGlvbnMudXNlVGFicyA9IGZhbHNlOwoJCQkJCXByZXR0aWVyT3B0aW9ucy50YWJXaWR0aCA9IDA7CgkJCQkJYnJlYWs7CgkJCQlkZWZhdWx0OgoJCQkJCXByZXR0aWVyT3B0aW9ucy51c2VUYWJzID0gZmFsc2U7CgkJCQkJcHJldHRpZXJPcHRpb25zLnRhYldpZHRoID0gMTsKCQkJfQoKCQkJc3dpdGNoIChlbmRPZkxpbmUpIHsKCQkJCWNhc2UgJ1xyXG4nOgoJCQkJCXByZXR0aWVyT3B0aW9ucy5lbmRPZkxpbmUgPSAnY3JsZic7CgkJCQkJYnJlYWs7CgkJCQljYXNlICdccic6CgkJCQkJcHJldHRpZXJPcHRpb25zLmVuZE9mTGluZSA9ICdjcic7CgkJCQkJYnJlYWs7CgkJCQljYXNlICdcbic6CgkJCQkJcHJldHRpZXJPcHRpb25zLmVuZE9mTGluZSA9ICdsZic7CgkJCQkJYnJlYWs7CgkJCQlkZWZhdWx0OgoJCQkJCXByZXR0aWVyT3B0aW9ucy5lbmRPZkxpbmUgPSAnYXV0byc7CgkJCX0KCQl9CgoJCXRyeSB7CgkJCW91dHB1dENvZGUgPSBwcmV0dGllci5mb3JtYXQoY29kZSwgewoJCQkJcGFyc2VyOiB0aGlzLnBhcnNlciwKCQkJCXBsdWdpbnM6IFtodG1sUGFyc2VyLCBiYWJlbFBhcnNlciwgbWFya2Rvd25QYXJzZXIsIHlhbWxQYXJzZXIsIHR5cGVzY3JpcHRQYXJzZXIsIHhtbFBhcnNlciwgbmdpbnhQYXJzZXJdLAoJCQkJLi4ucHJldHRpZXJPcHRpb25zLAoJCQl9KTsKCQkJY29uc29sZS5sb2cocHJldHRpZXJPcHRpb25zKTsKCQl9IGNhdGNoIChlKSB7CgkJCW9wdGlvbnMuZXJyb3JDYj8uKGUgYXMgRXJyb3IpOwoJCX0KCQlyZXR1cm4gb3V0cHV0Q29kZTsKCX0KCglQcm92aWRlU2FtcGxlQ29kZSgpOiBzdHJpbmcgewoJCWlmICh0aGlzLmxhbmcgPT09ICdodG1sJykgewoJCQlyZXR1cm4gJzxodG1sPjxib2R5PjxoMT5IZWxsbyBXb3JsZCE8L2gxPjwvYm9keT48L2h0bWw+JzsKCQl9CgoJCWlmICh0aGlzLmxhbmcgPT0gJ2phdmFzY3JpcHQnKSB7CgkJCXJldHVybiByYW5kQ29kZVNuaXBwZXQoJ2phdmFzY3JpcHQnKS5qb2luKCdcbicpOwoJCX0KCgkJaWYgKHRoaXMubGFuZyA9PSAndHlwZXNjcmlwdCcpIHsKCQkJcmV0dXJuIGB2YXIgY2FySW5zdXJhbmNlQ29tcGFueSA9IHsJbmFtZTogIkdlaWNvIixtYXJrZXRfY2FwaXRhbDogIiQzNC45IGJpbGxpb24iLCB9OyB2YXIgY2FySW5zdXJhbmNlQ29tcGFueU9iaiA9IEpTT04uc3RyaW5naWZ5KG9iaik7IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCJpbnN1cmFuY2UiKS5pbm5lckhUTUwgPSBjYXJJbnN1cmFuY2VDb21wYW55T2JqO2A7CgkJfQoKCQlpZiAodGhpcy5sYW5nID09ICdqc29uJykgewoJCQlyZXR1cm4gSlNPTi5zdHJpbmdpZnkoCgkJCQlyYW5kSlNPTih7CgkJCQkJbWluS2V5czogNSwKCQkJCQltYXhLZXlzOiAxMCwKCQkJCX0pID8/ICcnLAoJCQkpOwoJCX0KCgkJaWYgKHRoaXMubGFuZyA9PSAnbWFya2Rvd24nKSB7CgkJCXJldHVybiBgIyBNYXJrRG93biBTYW1wbGUKPT09PT09PT09PT09PT09PT09PT09PT09PT09PQoKICAgQWN0b3J8TW92aWV8SW5zdXJhbmNlCiAgIC0tfDotLTp8LS06CiAgIFRvbSBDcnVpc2V8TUk1fEdlaWNvCiAgQXJub2xkfFR1cmUgTGllc3xBbGxTdGF0ZQpgOwoJCX0KCgkJaWYgKHRoaXMubGFuZyA9PSAneWFtbCcpIHsKCQkJcmV0dXJuIGBDYXJJbnN1cmFuY2U6CiAgICAgICAgLSBDb21wYW55OiB7bmFtZTogU3RhdGUgRmFybSwgZm91bmRlZGluOiAxOTIyLCB3ZWJzaXRlOiB3d3cuc3RhdGVmYXJtLmNvbSB9CiAgICAgICAgLSBDb21wYW55OiB7bmFtZTogR2VpY28sIGZvdW5kZWRpbjogMTkzNiwgd2Vic2l0ZTogd3d3LmdlaWNvLmNvbSB9CmA7CgkJfQoJCWlmICh0aGlzLmxhbmcgPT0gJ25naW54JykgewoJCQlyZXR1cm4gYHNlcnZlciB7CiMgc2VydmVyIGRlZmluaXRpb24KbGlzdGVuIDQ0MyBzc2w7IGxpc3RlbiBbOjpdOjQ0MyBzc2w7CnNlcnZlcl9uYW1lIGV4YW1wbGUuY29tOwpsb2NhdGlvbiAvIHsgcHJveHlfcGFzcyBodHRwOi8vcHJveHk7IHByb3h5X3NldF9oZWFkZXIgSG9zdCAkaHR0cF9ob3N0Owpwcm94eV9zZXRfaGVhZGVyIFgtUmVhbC1JUCAkcmVtb3RlX2FkZHI7IHByb3h5X3NldF9oZWFkZXIgWC1Gb3J3YXJkZWQtRm9yICRwcm94eV9hZGRfeF9mb3J3YXJkZWRfZm9yOwpwcm94eV9zZXRfaGVhZGVyIFgtRm9yd2FyZGVkLVByb3RvICRzY2hlbWU7CnByb3h5X3JlYWRfdGltZW91dCAxMDAwOyB9CiMgZW5kIHNlcnZlciBkZWZpbml0aW9uCn1gOwoJCX0KCgkJcmV0dXJuICcoTm8gc2FtcGxlIGNvZGUgYXZhaWxhYmxlKSc7Cgl9Cn0K`;
		// return base64 decoded var codes
		return atob(codes);
	}

	if (lang == 'json') {
		return JSON.stringify(
			randJSON({
				minKeys: 5,
				maxKeys: 10,
			}) ?? '',
		);
	}

	if (lang == 'markdown') {
		const codes = `IyBNYXJrRG93biBTYW1wbGUKPT09PT09PT09PT09PT09PT09PT09PT09PT09PQoKICAgQWN0b3J8TW92aWV8SW5zdXJhbmNlCiAgIC0tfDotLTp8LS06CiAgIFRvbSBDcnVpc2V8TUk1fEdlaWNvCiAgQXJub2xkfFR1cmUgTGllc3xBbGxTdGF0ZQojIE1hcmtkb3duIHN5bnRheCBndWlkZQoKIyMgSGVhZGVycwoKIyBUaGlzIGlzIGEgSGVhZGluZyBoMQojIyBUaGlzIGlzIGEgSGVhZGluZyBoMiAKIyMjIyMjIFRoaXMgaXMgYSBIZWFkaW5nIGg2CgojIyBFbXBoYXNpcwoKKlRoaXMgdGV4dCB3aWxsIGJlIGl0YWxpYyogIApfVGhpcyB3aWxsIGFsc28gYmUgaXRhbGljXwoKKipUaGlzIHRleHQgd2lsbCBiZSBib2xkKiogIApfX1RoaXMgd2lsbCBhbHNvIGJlIGJvbGRfXwoKX1lvdSAqKmNhbioqIGNvbWJpbmUgdGhlbV8KCiMjIExpc3RzCgojIyMgVW5vcmRlcmVkCgoqIEl0ZW0gMQoqIEl0ZW0gMgoqIEl0ZW0gMmEKKiBJdGVtIDJiCgojIyMgT3JkZXJlZAoKMS4gSXRlbSAxCjEuIEl0ZW0gMgoxLiBJdGVtIDMKICAxLiBJdGVtIDNhCiAgMS4gSXRlbSAzYgoKIyMgSW1hZ2VzCgohW1RoaXMgaXMgYSBhbHQgdGV4dC5dKC9pbWFnZS9zYW1wbGUucG5nICJUaGlzIGlzIGEgc2FtcGxlIGltYWdlLiIpCgojIyBMaW5rcwoKWW91IG1heSBiZSB1c2luZyBbTWFya2Rvd24gTGl2ZSBQcmV2aWV3XShodHRwczovL21hcmtkb3dubGl2ZXByZXZpZXcuY29tLykuCgojIyBCbG9ja3F1b3RlcwoKPiBNYXJrZG93biBpcyBhIGxpZ2h0d2VpZ2h0IG1hcmt1cCBsYW5ndWFnZSB3aXRoIHBsYWluLXRleHQtZm9ybWF0dGluZyBzeW50YXgsIGNyZWF0ZWQgaW4gMjAwNCBieSBKb2huIEdydWJlciB3aXRoIEFhcm9uIFN3YXJ0ei4KPgo+PiBNYXJrZG93biBpcyBvZnRlbiB1c2VkIHRvIGZvcm1hdCByZWFkbWUgZmlsZXMsIGZvciB3cml0aW5nIG1lc3NhZ2VzIGluIG9ubGluZSBkaXNjdXNzaW9uIGZvcnVtcywgYW5kIHRvIGNyZWF0ZSByaWNoIHRleHQgdXNpbmcgYSBwbGFpbiB0ZXh0IGVkaXRvci4KCiMjIFRhYmxlcwoKfCBMZWZ0IGNvbHVtbnMgIHwgUmlnaHQgY29sdW1ucyB8CnwgLS0tLS0tLS0tLS0tLSB8Oi0tLS0tLS0tLS0tLS06fAp8IGxlZnQgZm9vICAgICAgfCByaWdodCBmb28gICAgIHwKfCBsZWZ0IGJhciAgICAgIHwgcmlnaHQgYmFyICAgICB8CnwgbGVmdCBiYXogICAgICB8IHJpZ2h0IGJheiAgICAgfAoKIyMgQmxvY2tzIG9mIGNvZGUKCmBgYApsZXQgbWVzc2FnZSA9ICdIZWxsbyB3b3JsZCc7CmFsZXJ0KG1lc3NhZ2UpOwpgYGAKCiMjIElubGluZSBjb2RlCgpUaGlzIHdlYiBzaXRlIGlzIHVzaW5nIGBtYXJrZWRqcy9tYXJrZWRgLg==`;
		return atob(codes);
	}

	if (lang == 'yaml') {
		return `CarInsurance:
        - Company: {name: State Farm, foundedin: 1922, website: www.statefarm.com }
        - Company: {name: Geico, foundedin: 1936, website: www.geico.com }
`;
	}

	if (lang == 'nginx') {
		return `server {
# server definition
listen 443 ssl; listen [::]:443 ssl;
server_name example.com;
location / { proxy_pass http://proxy; proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_read_timeout 1000; }
# end server definition
}`;
	}
	return '(No sample code available)';
}
